# Generated by Django 6.0.1 on 2026-01-13 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_stock", models.IntegerField(default=0)),
                ("minimum_stock_level", models.IntegerField()),
                ("maximum_stock_level", models.IntegerField()),
                ("safety_stock", models.IntegerField()),
                ("reorder_quantity", models.IntegerField()),
                (
                    "holding_cost_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_level",
                        to="forecasting.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound (Purchase)"),
                            ("outbound", "Outbound (Sale)"),
                            ("adjustment", "Adjustment"),
                            ("return", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.inventorylevel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventorylevel",
            index=models.Index(
                fields=["current_stock"], name="inventory_i_current_70e920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["inventory", "created_at"],
                name="inventory_s_invento_7edcad_idx",
            ),
        ),
    ]
