# Generated by Django 6.0.1 on 2026-01-13 10:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=100)),
                (
                    "unit_of_measurement",
                    models.CharField(default="units", max_length=50),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        default=7,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["sku"], name="forecasting_sku_be9d67_idx"),
                    models.Index(
                        fields=["category"], name="forecasting_categor_ae25a7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("arima", "ARIMA"),
                            ("xgboost", "XGBoost"),
                            ("prophet", "Prophet"),
                            ("moving_avg", "Moving Average"),
                            ("ensemble", "Ensemble"),
                        ],
                        max_length=20,
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "predicted_demand",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "confidence_interval_lower",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "confidence_interval_upper",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("mae", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("mape", models.FloatField(blank=True, null=True)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("forecast_horizon_days", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="forecasting.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="ForecastDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("predicted_quantity", models.FloatField()),
                ("lower_bound", models.FloatField()),
                ("upper_bound", models.FloatField()),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="forecasting.forecast",
                    ),
                ),
            ],
            options={
                "ordering": ["forecast_date"],
                "unique_together": {("forecast", "forecast_date")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalDemand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "quantity_demanded",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "actual_sales",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "external_factors",
                    models.JSONField(
                        default=dict, help_text="Weather, holidays, promotions, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_demands",
                        to="forecasting.product",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="forecasting_product_41c5b3_idx",
                    )
                ],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["product", "forecast_date"],
                name="forecasting_product_d8651b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(fields=["status"], name="forecasting_status_1cc8ef_idx"),
        ),
    ]
